language: java
sudo: false
jdk: oraclejdk8

install:
  ./gradlew setupCIWorkspace
script:
  ./gradlew build

deploy:
  - provider: script
    script: ./gradlew githubRelease
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew curseforge
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper/