language: java
sudo: false
jdk: oraclejdk8

install:
  ./gradlew setupCIWorkspace

before_script:
  - mkdir lib
  - curl -o lib/Thaumcraft-1.12.2-6.1.BETA26-deobf.jar -L https://www.dropbox.com/s/jex9q8g1tril3uo/Thaumcraft-1.12.2-6.1.BETA26-deobf.jar?dl=1

script:
  ./gradlew build

deploy:
  - provider: script
    script: ./gradlew githubRelease
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew curseforge
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper/